- lib/service/user.go
Initialized is an internal state before the invoice was created on LND.
We should not expose those. If an invoice is in that state it means it is either currently created or something went wrong.
> Do not return invoices that are in the initialized state

- .github/workflows/workflow.yaml
Deploys all pushes to master to the dev environment, only deploys tagged versions of master to production environment.
> add CD steps to build workflow

- controllers/addinvoice.ctrl.go
- controllers/auth.ctrl.go
- controllers/balance.ctrl.go
- controllers/checkpayment.ctrl.go
- controllers/create.ctrl.go
- controllers/getinfo.ctrl.go
- controllers/gettxs.ctrl.go
- controllers/home.ctrl.go
- controllers/payinvoice.ctrl.go
- lib/service/invoices.go
- lib/service/service.go
- lib/service/user.go
Reference issue: https://github.com/getAlby/lndhub.go/issues/55
There are 2 methods for creating contexts, context.Background() and context.TODO(). They both return empty context, only difference is in name: TODO should be used on places where we are not sure about if we need context, or context behavior.
However, it seems that repo currently passes context to external package db methods, and I assume that is because this context can be used to timeout or cancel db operations. Using TODO doesn't make much sense here since we are just passing context to these methods, but we know the usage, so we should pass in parent context.
According to this https://www.ardanlabs.com/blog/2019/09/context-package-semantics-in-go.html
Incoming requests to a server should create a Context, but because …
> Remove context todo

- controllers/auth.ctrl.go
- controllers/create.ctrl.go
This PR is more for discussion, please read this summary:
It looks like sentry is capturing exceptions in 2 ways, either in generic http response handler, or manually calling CaptureException method. Issue is mentioning one example of sensitive data captured, refresh and access token, and that should be fixed with this commit https://github.com/getAlby/lndhub.go/pull/116/commits/f615564728909b241e322d5151ddd14d3f99ba68.
Below is summary of other places where this can occur, I don't think there is more sensitive data, apart from UserID comment:
```
did we change something that this userId is no longer sent to sentry:
https://github.com/getAlby/lndhub.go/blob/main/lib/responses/errors.go#L46-L50
```
^ does this mean that there is a bug with userId not being sent or?
1. controllers returning …
> Sensitive data from sentry payload

- .github/workflows/build_binaries.yaml
In practice, lndhub will always run on a linux server, so there is no need for any other binaries.
> add build workflow

- main.go
Half of our alerts are because certain versions of Google Chrome look for the favicon on `/favicon.ico` instead of what is defined in the meta tags in index.html.
> add favicon.ico rewrite

- integration_tests/auth_test.go
- integration_tests/checkpayment_test.go
- integration_tests/create_test.go
- integration_tests/expected_requests_and_responses.go
- integration_tests/getinfo_test.go
- integration_tests/gettxs_test.go
- integration_tests/incoming_payment_test.go
- integration_tests/internal_payment_test.go
- integration_tests/invoice_test.go
- integration_tests/keysend_test.go
- integration_tests/payment_failure_async_test.go
- integration_tests/payment_failure_test.go
- integration_tests/util.go
Added expected response and request structs for all integration tests, so in case they change on endpoints tests will fail.
> Add and use expected requests and responses for integration tests

- controllers/payinvoice.ctrl.go
When testing out Alby and Bluewallet on regtest, I noticed that Bluewallet puts in the invoice uppercase when calling `payinvoice`. This caused internal Alby payments to fail, as Alby could not find the invoice in the db.
> always lowercase payreq

- .github/workflows/workflow.yaml
To easily test out new features, all branches should be containerized. However, only pushes to the main branch will be auto-deployed to the  dev environment.
> always build docker images on every branch

- integration_tests/incoming_payment_test.go
- lib/service/invoicesubscription.go
Fixes #165 
This credits the user's account the full amount that was paid for all incoming invoices. When there is a mismatch, a line is logged.
I pushed an integration test that reproduces the bug in the first commit.
> Fix: 0 amount incoming invoice

- controllers/addinvoice.ctrl.go
- controllers/checkpayment.ctrl.go
- controllers/keysend.ctrl.go
- controllers/payinvoice.ctrl.go
This should help analyzing the logs better for a specific user.
Also this more unifies the logs to use `:` as key separator. (e.g. `user_id:%v`)
> Log user ids on more errors

- controllers/getinfo.ctrl.go
- controllers/home.ctrl.go
This tells clients to cache the response for a few minutes and
thus makes it easier to run lndhub behind a proxy to cache static response
> Set cache-control headers for static routes (getinfo and home)

- integration_tests/subscription_start_test.go
- lib/service/invoicesubscription.go
Currently we checked all payments which means we start the subscription from an index for an invoice that can no longer be paid because it is expired.
And because it is expired we do not need to listen for updates for it anymore
> Fix: start invoice subscription from last NOT expired invoice

- controllers/invoicestream.ctrl.go
Found by running the latest `staticcheck` from https://github.com/dominikh/go-tools
Full report, but the rest are only nits (unused fields, deprecated fields, error string capitalization)
```
$ staticcheck ./...
controllers/invoicestream.ctrl.go:52:2: should check returned error before deferring ws.Close() (SA5001)
integration_tests/subscription_start_test.go:31:2: field invoiceUpdateSubCancelFn is unused (U1000)
integration_tests/websocket_test.go:137:2: this value of err is never used (SA4006)
lib/service/invoices.go:141:54: sendPaymentResult.PaymentRoute.TotalAmt is deprecated: Do not use.  (SA1019)
lib/service/invoices.go:141:106: sendPaymentResult.PaymentRoute.TotalFees is deprecated: Do not use.  (SA1019)
lib/service/invoicesubscription.go:66:10: error strings should not be …
```
> Don't defer close when the creation failed

- README.md
- legacy_endpoints.go
- lib/service/config.go
- v2_endpoints.go
This covers the usecase when LndHub is used to serve closed communities
which do not want to accept new members anymore (friends, families, etc).
The PR introduces a new envconfig option CREATE_ACCOUNTS which is true
by default but can be set to false if needed.
> Make it possible to disable account creation

- controllers/auth.ctrl.go
- controllers_v2/create.ctrl.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
Since we're using `login` everywhere else, we should be consistent.
> replace username by login

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- main.go
* There are lot of places where we are stuck at 0.6.1 while the latest version is 0.9.0
* Fix license identifier (GPL -> GPLv3) to make it more obvious which version is being used
> Fix version in documentation

- db/db.go
According to Pgdriver documentation a valid connection string can also start with `unix://` when UNIX sockets are used. See https://bun.uptrace.dev/postgres/#pgdriver
This PR updates the checks to allow that.
> Enable "unix:" prefix for PostgreSQL connection string

- README.md
- lib/service/config.go
- main.go
Extracted from https://github.com/getAlby/lndhub.go/pull/217
> macaroon and cert can be provided as files

- README.md
- go.mod
- go.sum
- lib/service/config.go
- lib/service/user.go
that allows an operator to set minimum entropy (in bits) of a password to be accepted during account creation
> Introduce config.MinPasswordEntropy option

- controllers/payinvoice.ctrl.go
Fixes #223 , testing on testnet when build is ready.
> don't omit payment error when empty

- controllers/keysend.ctrl.go
- controllers/payinvoice.ctrl.go
- controllers_v2/keysend.ctrl.go
- controllers_v2/payinvoice.ctrl.go
- db/models/invoice.go
- integration_tests/internal_payment_test.go
- lib/service/invoices.go
- lib/service/invoices_test.go
Closes #233 
In case of an internal payment, the fee reserve should be 0.
This change allow clients to create a "Drain account" UX by combining different calls:
- make a payment (or more than 1) leaving just the fee reserve in the account, using a Lightning Address or 0 amount invoice.
- send the rest of the funds to some internal wallet (eg. hello@getalby.com or someone else).
> set fee reserve to 0 if destination is us

- controllers/payinvoice.ctrl.go
- controllers_v2/payinvoice.ctrl.go
This prevents polluting the database with invoices that will never be paid.
Makes the process of checking invoices states at startup more efficient, because we won't be checking invoices that LND doesn't know anything about.
> delete invoices when balance check fails

- lib/service/invoices.go
Fixes #286 
This brings handling a failed payment in line with the way we add incoming payments to a user's account.
> atomic failed payment handling

- db/migrations/20230113103000_tx_entry_unique_constraint.up.sql
Fixes #155 
Reproducing the bug: https://www.loom.com/share/a45b23b389b847c4a83ae34edb1ab299
Note that this doesn't really solve an issue with the database connection between the 2 db transactions in `HandleFailedPayment`, for that we need to implement #286 . But this would prevent inconsitent data in the db.
> add tx entry tuple constraint

- controllers/keysend.ctrl.go
- controllers_v2/keysend.ctrl.go
- lib/responses/errors.go
Fixes #270 
Tested locally. 
```
➜  Alby http POST localhost:3000/v2/payments/keysend < keysend.json Authorization:"Bearer $token"
HTTP/1.1 400 Bad Request
Content-Length: 110
Content-Type: application/json; charset=UTF-8
Date: Mon, 09 Jan 2023 14:02:42 GMT
X-Request-Id: vddq9Yq3JPt5gYj5QSGk91cpcL4NYWye
{
"code": 8,
"error": true,
"message": "Internal keysend payments require the custom record 696969 to be present."
}
```
Other endpoints can also be updated to use the status code from `ErrorResponse` to improve the accuracy of the http status code returned. However this should be for another PR.
> more accurate http status codes for keysend

- db/db.go
- integration_tests/subscription_start_test.go
- lib/service/config.go
- lib/service/invoicesubscription.go
- main.go
Fixes #312 , fixes #313 
This PR changes the behaviour of the invoice subscription routine in case of an error:
- If the database call at startup time fails, we return an error which will crash LNDhub and force a restart. 
- If the `Recv()` call fails (probably because LND is down), then we will also force LNDhub to restart, so it can try to reconnect to LND.
Other than that
- It introduces a database timeout config option, with a default value of 1 minutes (up from 5 seconds)
- It introduces a safety buffer of 14 hours to make sure we absolutely did not miss any invoices which might have been paid while LNDhub was down.
> Invoice subscription: safety improvements

- db/migrations/2023021603000_invoice_expiresat.sql
Follow-up for #316 
This query is executed at startup: 
`select * from invoices where 
invoices.settled_at IS NULL AND 
invoices.add_index IS NOT NULL AND
invoices.expires_at >= (now() - interval '14 hours') 
order by invoices.id asc
limit 1 `
This PR adds an index on `expires_at` to speed up this query. I chose this column because it's the most restrictive one and leaves us just with 14 hours of invoice rows that need to be scanned (instead of the whole table). 
Test results from running on `testnet`: 
Speeded up the query from ~6s down to < 10ms.
> feat: db index for subscriptions query

- main.go
- rabbitmq/rabbitmq.go
Fixes #345 
In case the connection to RabbitMQ is lost due to networking error or RabbitMQ being down, the channel will be closed and lndhub should be restarted to try and reconnect again.
> prevent EOF loop

- README.md
- main.go
- Fix docs
- Remove default rate limit for non-strict endpoints
- Change strict endpoint rate limiting to requests / second (instead of every X seconds)
- Rate limit based on user id (if available, instead of IP) ➡️ NWC
> fix: improve rate limit handling

- go.mod
- legacy_endpoints.go
- main.go
- v2_endpoints.go
Replaces #361 
Creates the log middleware with an Enricher and injects it after the JWT middleware.
There is some code duplication because of the secured/unsecured API groups, but all in all I think it's ok.
As an example, when trying to pay a misformed invoice
Log output before (no seperate UserID field):
```
{"level":"error","id":"1ihPmGY73JFRby8AEj7ZHmN6OwiyMclO","time":"2023-05-23T19:34:23+02:00","message":"Invalid payment request user_id:26 error: rpc error: code = Unknown desc = invalid bech32 string length 3"}
{"level":"debug","id":"1ihPmGY73JFRby8AEj7ZHmN6OwiyMclO","remote_ip":"::1","host":"localhost:3000","method":"POST","uri":"/payinvoice","user_agent":"HTTPie/3.2.1","status":400,"referer":"","latency":48.579542,"latency_human":"48.579542ms","bytes_in":"18","bytes_out":"50","time …
```
> add user id to logs as json field

- lib/service/invoicesubscription.go
In case of after-the-fact updates of missed invoices (republished on rabbitmq), these must also be updated.
> don't require incoming invoices to be non-expired

- controllers/keysend.ctrl.go
- controllers_v2/keysend.ctrl.go
- integration_tests/internal_payment_test.go
- integration_tests/lnd_mock.go
- integration_tests/subscription_start_test.go
- integration_tests/util.go
- lib/service/invoices.go
- lib/service/invoices_test.go
- lib/service/invoicesubscription.go
- lib/service/service.go
- lib/service/user.go
- lnd/interface.go
- lnd/lnd.go
- main.go
- reconciliation_lost_invoices/main.go
This PR prepares for a multi-LND backend by moving the "is this our pubkey?" checks to the LND client, so that it will also work with multiple backend nodes. For simplicity is also 1 "main" public key that acts as a placeholder public key to use for all incoming invoices, but this will not necessarily mean that these invoices will be generated by the node with that public key in case of multiple backend nodes.
> Refactor: move pubkey logic to lnd domain

- init_echo.go
- main.go
In my refactoring enthusiasm I've introduced a bug that stopped APM for LNDhub.go 😅 . 
the `defer tracer.Stop()` causes the tracer to stop immediately if not called from main.go.
> move dd tracer start back to main

- lnd/config.go
- lnd/ln_client.go
Tested and this seems like it can work.
This removes the need to crash when we can't connect to one of the LND nodes at startup, which can happen when the Lightning nodes & the LNDHub pods are all restarted at the same time.
We get the public keys of the nodes by putting them in the configuration. That way we can know which invoices are internal and which are external.
> remove getinfo call when initializing cluster

- cmd/payment-reconciliation/main.go
- integration_tests/hodl_invoice_test.go
- lib/service/background_routines.go
- lib/service/checkpayments.go
Partial fix for #445  (still need deployment)
Since there still seem to be payments that are not being credited after a HODL invoice is settled, we must deploy a cron job to periodically check the pending payments in the database and track their status with LND.
Because we run this in a job and we want to avoid recent HODL payments, we only check the status of invoices older than 24h (and younger than 2 weeks). We also use a timeout to be sure this job doesn't keep on running.
The `cmd/payment-reconciliation` folder is already being built and added as a binary to the docker container. So to run this as a cron job, we just have to overwrite the containers default command.
> Refactor reconciliation

- controllers_v2/keysend.ctrl.go
Moves `CheckPaymentAllowed` check one level up so that it doesn't add much load by triggering everytime during multikeysend checks
> chore: optimize keysend/multikeysend balance checks

- controllers/gettxs.ctrl.go
As discussed on [slack](https://getalby.slack.com/archives/C02TDCWNX0T/p1696837586971999)
This stops failed payments from showing up in Zeus.
> legacy endpoint: no errored invoices

- integration_tests/hodl_invoice_test.go
- integration_tests/internal_payment_test.go
- integration_tests/keysend_failure_test.go
- integration_tests/payment_failure_async_test.go
- integration_tests/payment_failure_test.go
- integration_tests/util.go
- lib/service/user.go
> fix: exclude erroneous payments

- Makefile
- cmd/server/main.go
- controllers_v2/update.ctrl.go
- db/migrations/20240103130000_add_deleted_to_users.up.sql
- db/models/user.go
- integration_tests/deactivated_deleted_test.go
- integration_tests/util.go
- lib/service/service.go
- lib/service/user.go
- lib/tokens/jwt.go
This allows users to be marked as deleted.
An additional middleware checks if a user is deleted or deactivated and rejects
requests for those as StatusUnauthorized.
note: the middelware adds an additional DB query to load the user.
[closes #468]
> Soft delete users

- .github/workflows/workflow.yaml
Merge must be coordinated with
getAlby/alby-deployment#230
which splits values.yaml file for simnet cluster into values/*.yaml for each deployment
>  update simnet yaml files inside values

- Makefile
- README.md
- db/migrations/20231229091800_add_service_fee.up.sql
- db/models/invoice.go
- db/models/transactionentry.go
- integration_tests/keysend_test.go
- integration_tests/outgoing_payment_test.go
- integration_tests/payment_failure_test.go
- integration_tests/util.go
- lib/service/checkpayments.go
- lib/service/config.go
- lib/service/invoices.go
- lib/service/invoices_test.go
- lib/service/user.go
- rabbitmq/rabbitmq.go
This introduces a new transaction type "service_fee". 
Each outgoing payment is charged a service fee of x/1000. The service fee entries is added with the routing fee reserve entry. For failed payments the service fee is reversed.
A threshold up to which transactions are free can be configured (`NO_SERVICE_FEE_UP_TO_AMOUNT`)
> Add support for service fees

- db/migrations/20231123030000_add_amount_to_transaction_entries_index.up.sql
Speed up the `check_balance()` trigger that is being run after every payment.
> feat: include amount in index

- integration_tests/internal_payment_test.go
- integration_tests/invoice_test.go
- integration_tests/keysend_test.go
- integration_tests/outgoing_payment_test.go
- integration_tests/util.go
- lib/service/config.go
- lib/service/user.go
- lib/tokens/jwt.go
Post this, if we wish to remove the limit we use -1 (not 0)
And this is only for `MaxSendVolume`, `MaxSendAmount`, `MaxReceiveVolume`, `MaxReceiveAmount`
*Everything in limits except `MaxAccountBalance`
> chore: allow 0 limits for send/receive amount/volume

- controllers_v2/keysend.ctrl.go
- controllers_v2/payinvoice.ctrl.go
So far we have returned the total amount (which includes the fee) and the fee. This information was taken from the payment route response now we directly return it from the invoice data. This is consistent with the other transaction responses
> Return correct Amount and Fee on the payment responses
