controllers/addinvoice.ctrl.go
controllers/auth.ctrl.go
controllers/checkpayment.ctrl.go
controllers/payinvoice.ctrl.go
lib/responses/errors.go
lib/service/invoices.go

This is not exactly the response that lndhub gives but it should be good enough.
This PR also DRYs up the error responses

Better payinvoice response + DRY errors

---

controllers/addinvoice.ctrl.go
controllers/auth.ctrl.go
controllers/payinvoice.ctrl.go
lib/responses/errors.go
lib/service/invoices.go
lib/service/invoicesubscription.go
main.go

Sentry notifications

---

lib/service/invoices.go

Very small amounts have problems with the percentage based fee limit.
This has to be changed soon to be smarter and more dynamic (#81 )

Set fixed fee limit

---

controllers/gettxs.ctrl.go
integration_tests/create_test.go
integration_tests/gettxs_test.go
integration_tests/incoming_payment_test.go
integration_tests/internal_payment_test.go
integration_tests/outgoing_payment_test.go
integration_tests/util.go

- Added tests for gettxs ctrl.
- Moved some common code to util file
- Left comments on places for discussion points

Get incoming/outgoing invoices tests

---

controllers/checkpayment.ctrl.go
integration_tests/checkpayment_test.go
integration_tests/getinfo_test.go

Adding the rest of integration tests to complete integration tests issue.

Payment and info tests

---

db/migrations/20220120000700_add_constraints.up.go
db/migrations/20220308103000_replace_check_balance.up.go

failing test fixed in https://github.com/getAlby/lndhub.go/pull/129

Fix migration

---

controllers/addinvoice.ctrl.go
controllers/invoice.ctrl.go
integration_tests/invoice_test.go
integration_tests/util.go
lib/service/user.go
main.go

Used the same logic as addInvoice, just getting user from db first instead of getting it from token.

Unauthorized invoice endpoint

---

controllers/payinvoice.ctrl.go
integration_tests/checkpayment_test.go
integration_tests/gettxs_test.go
integration_tests/internal_payment_test.go
integration_tests/outgoing_payment_test.go
integration_tests/util.go

- Add 0 amount check in controller
- Refactor tests
- Add test for paying 0 amount invoice

Feature: pay 0 amount invoice

---

lib/service/webhook.go

add user login to webhook payload

---

controllers/payinvoice.ctrl.go
lib/tokens/jwt.go

Extend sentry with some mode debugging information

---

README.md
controllers/keysend.ctrl.go
controllers/payinvoice.ctrl.go
db/models/invoice.go
lib/service/config.go
lib/service/invoices.go
lib/service/invoices_test.go

My shot at fixing/implementing https://github.com/getAlby/lndhub.go/issues/183
It's rather naive and I am not sure if having the check at one place only is enough.
Someone with more Go expertise than me should carefully review.
And yeah, this PR does not contain any tests ... :-/

Implement fee-reserve

---

README.md

Fixes https://github.com/getAlby/lndhub.go/issues/213

readme: add satoshi units to readme

---

controllers/invoicestream.ctrl.go

add custom records

---

static/css/style.css

Proper custom logo scaling

---

controllers/payinvoice.ctrl.go
controllers_v2/payinvoice.ctrl.go

After testing on testnet (didn't test locally), it seems that the previous PR didn't do anything.
(I'll test locally first in the future I promise)

fix bug: no model needed here

---

README.md
controllers_v2/keysend.ctrl.go
docs/docs.go
docs/swagger.json
docs/swagger.yaml
integration_tests/keysend_test.go
v2_endpoints.go

This PR fixes #230
Request:
Response:
The response can contain both succesful and failed keysend payments.

add multikeysend endpoint

---

controllers_v2/keysend.ctrl.go

fix: check splits multikeysend body

---

controllers_v2/keysend.ctrl.go

feature: return custom records

---

lib/service/invoices.go

invoice: lookup more performant by hash

---

main.go

Split sentry config as described in the docs

---

controllers_v2/invoice.ctrl.go
integration_tests/expected_requests_and_responses.go
integration_tests/invoice_test.go

allow 0 amount invoices in v2 api

---

controllers_v2/keysend.ctrl.go

Moving the workaround to be above the internal payment check we prevent a bug in the check for internal payments.

move custom records workarounds up

---

db/db.go
integration_tests/util.go
lib/service/config.go
main.go

feature: add db pool config

---

Dockerfile
go.mod
go.sum

Upgrade to go 1.20

---

common/globals.go
controllers/keysend.ctrl.go
controllers/payinvoice.ctrl.go
controllers_v2/keysend.ctrl.go
controllers_v2/payinvoice.ctrl.go
integration_tests/keysend_test.go
integration_tests/lnd_mock.go
integration_tests/payment_failure_test.go
lib/responses/errors.go

Fixes #315
Not sure about this:

feat: add checks and remove sentry logging

---

lib/service/config.go
rabbitmq/rabbitmq.go

Change default name for invoice consumer to lnd_invoice_consumer

---

rabbitmq/rabbitmq.go

don't requeue on error

---

background_routines.go
init_echo.go
main.go

Just moving some stuff in their own files to make things more readable.

refactor: make main.go smaller

---

controllers/addinvoice.ctrl.go
controllers/auth.ctrl.go
controllers/balance.ctrl.go
controllers/getinfo.ctrl.go
controllers/gettxs.ctrl.go
controllers/home.ctrl.go
controllers/keysend.ctrl.go
controllers/payinvoice.ctrl.go
controllers_v2/balance.ctrl.go
controllers_v2/invoice.ctrl.go
controllers_v2/keysend.ctrl.go
controllers_v2/payinvoice.ctrl.go

chore: add missing logs

---

controllers/keysend.ctrl.go
integration_tests/keysend_failure_test.go
lib/service/invoices.go
lib/service/invoicesubscription.go

chore: add rhash and preimage to invoice before failure

---

controllers_v2/keysend.ctrl.go

feat: use background context in multikeysend

---

lnd/lnd_cluster.go

feat: introduce timeout in cluster status check

---

README.md
controllers/addinvoice.ctrl.go
controllers_v2/invoice.ctrl.go
integration_tests/internal_payment_test.go
integration_tests/invoice_test.go
lib/responses/errors.go
lib/service/invoices.go

Adds checks for `MaxAccountBalance`, `MaxReceiveAmount` and `MaxVolume` in `AddIncomingInvoice` itself to avoid repetition in v1 and v2 controllers

chore: add exceeding checks for volume, balance, receive

---

controllers/keysend.ctrl.go
controllers/payinvoice.ctrl.go
controllers_v2/keysend.ctrl.go
controllers_v2/payinvoice.ctrl.go
integration_tests/internal_payment_test.go
lib/responses/errors.go
lib/service/invoices.go

Fixes #461 (?)
Adds checks for `MaxSendAmount` in `AddOutgoingInvoice` itself to avoid repetition in v1 and v2 controllers

chore(addoutgoinginvoice): add exceeding checks for send

---

lib/service/user.go
lib/tokens/jwt.go

this helps debugging potential issues

Add logs to outgoing/incoming limit checks
